name: AWS-MLOPS
on: [push]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: printing
        run: echo "CI step Init" 

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip 
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check rag-app exists
        run: ls && pwd
      
      - name: Run test
        run: pytest -v
        working-directory: rag-app-simple